# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Submit a new beta build to Google Play"
  lane :beta do
    sh "flutter pub get"
    sh "flutter build appbundle -v"
    upload_to_play_store(
      track: 'beta',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
      )
  end

  desc "Promote beta track to prod"
  lane :promote_to_production do
    upload_to_play_store(
      track: 'beta',
      track_promote_to: 'production',
      skip_upload_changelogs: true,
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
      )
  end

  desc "Submit a new production build to Google Play"
  lane :production do
    sh "flutter pub get"
    sh "flutter build appbundle -v"
    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
    )
  end
end

lane :bump_version do |options|
  current_version = flutter_bump_version(
    arguments: options,
    pubspec: "../pubspec.yaml"
  )
  # if(current_version != 'not_bump' && options[:push])
  #   git_commit(path: "../pubspec.yaml", message: "bump version to #{current_version} from fastlane")
  #   push_to_git_remote
  # end
end
